apiVersion: v1
kind: Service
metadata:
  name: svc-lb-kubernet
  labels:
     app: myjavaapp
spec:
  type: LoadBalancer
  selector:
    app: myjavaapp
  ports:
  - nodePort: 31000
    protocol: TCP
    port: 80
    targetPort: 80