apiVersion: v1
kind: Service
metadata:
  name: svc-lb-kubernet
spec:
  type: LoadBalancer
  selector:
    tag: label-kubetrain
  ports:
  - name: port-lb-kubtrain
    protocol: TCP
    port: 8080
    targetPort: 80