apiVersion: v1
kind: Service
metadata:
  name: svc-lb-kubernet
  labels:
     app: myjavaapp
  spec:
  type: LoadBalancer
  selector:
    app: myjavaapp
  ports:
  - port: 8080
    nodePort: 31005
    protocol: TCP
    targetPort: 80
    
  